#ifndef JMEVM_CORE_BYTECODE_H
#define JMEVM_CORE_BYTECODE_H

#define JMEVM_OP_ICONST_M1 0x02
#define JMEVM_OP_ICONST_0 0x03
#define JMEVM_OP_ICONST_1 0x04
#define JMEVM_OP_ICONST_2 0x05
#define JMEVM_OP_ICONST_3 0x06
#define JMEVM_OP_ICONST_4 0x07
#define JMEVM_OP_ICONST_5 0x08

#define JMEVM_OP_ILOAD 0x15
#define JMEVM_OP_ILOAD_0 0x1a
#define JMEVM_OP_ILOAD_1 0x1b
#define JMEVM_OP_ILOAD_2 0x1c
#define JMEVM_OP_ILOAD_3 0x1d

#define JMEVM_OP_ISTORE 0x36
#define JMEVM_OP_ISTORE_0 0x3b
#define JMEVM_OP_ISTORE_1 0x3c
#define JMEVM_OP_ISTORE_2 0x3d
#define JMEVM_OP_ISTORE_3 0x3e

#define JMEVM_OP_IADD 0x60
#define JMEVM_OP_ISUB 0x64

#define JMEVM_OP_INVOKESTATIC 0xb8

#define JMEVM_OP_GETSTATIC 0xb2
#define JMEVM_OP_INVOKEVIRTUAL 0xb6
#define JMEVM_OP_INVOKESPECIAL 0xb7
#define JMEVM_OP_DUP 0x59

#define JMEVM_OP_IRETURN 0xac

#define JMEVM_OP_RETURN 0xb1
#define JMEVM_OP_NEW 0xbb
#define JMEVM_OP_GETFIELD 0xb4
#define JMEVM_OP_PUTFIELD 0xb5

#define JMEVM_OP_BIPUSH 0x10
#define JMEVM_OP_SIPUSH 0x11
#define JMEVM_OP_LDC 0x12

#define JMEVM_OP_ALOAD 0x19
#define JMEVM_OP_ALOAD_0 0x2a
#define JMEVM_OP_ALOAD_1 0x2b
#define JMEVM_OP_ALOAD_2 0x2c
#define JMEVM_OP_ALOAD_3 0x2d

#define JMEVM_OP_ASTORE 0x3a
#define JMEVM_OP_ASTORE_0 0x4b
#define JMEVM_OP_ASTORE_1 0x4c
#define JMEVM_OP_ASTORE_2 0x4d
#define JMEVM_OP_ASTORE_3 0x4e

#define JMEVM_OP_IALOAD 0x2e
#define JMEVM_OP_BALOAD 0x33

#define JMEVM_OP_IASTORE 0x4f
#define JMEVM_OP_BASTORE 0x54

#define JMEVM_OP_ARRAYLENGTH 0xbe

#define JMEVM_OP_NEWARRAY 0xbc

#endif
