#!/usr/bin/env bash
# cldc/gen_headers.sh
# Compiles every Java source under cldc/classes/ and turns each resulting
# .class into a C header with an embedded static byte array.
#
# Headers are written to  cldc/generated/<SimpleName>.h
#
# Usage (from project root):
#   ./cldc/gen_headers.sh
#   JAVAC=javac8 ./cldc/gen_headers.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$SCRIPT_DIR/classes"
GEN_DIR="$SCRIPT_DIR/generated"
JAVAC="${JAVAC:-javac}"
JAVAC_FLAGS="${JAVAC_FLAGS:--Xlint:-options -source 8 -target 8}"

mkdir -p "$GEN_DIR"

echo "[cldc] Compiling Java sources..."

mapfile -t SOURCES < <(find "$SRC_DIR" -name "*.java")
if [ ${#SOURCES[@]} -eq 0 ]; then
    echo "[cldc] No Java sources found in $SRC_DIR"
    exit 0
fi

# Compile all at once so javac can resolve cross-class deps
# shellcheck disable=SC2086
"$JAVAC" $JAVAC_FLAGS -d "$SRC_DIR" "${SOURCES[@]}" 2>&1 \
    | grep -v "^Note:" || true

echo "[cldc] Compilation done."
echo "[cldc] Generating C headers in $GEN_DIR..."

for src in "${SOURCES[@]}"; do
    dir="$(dirname "$src")"
    base="$(basename "$src" .java)"
    cls="$dir/${base}.class"

    if [ ! -f "$cls" ]; then
        echo "  [warn] $cls not found, skipping"
        continue
    fi

    # Relative path from SRC_DIR, e.g. java/lang/Foo
    rel_noext="${cls#"$SRC_DIR/"}"
    rel_noext="${rel_noext%.class}"

    # C variable name: java_lang_Foo_class
    varname="$(echo "$rel_noext" | tr '/' '_')_class"

    header="$GEN_DIR/${base}.h"

    # Use Python to reliably convert binary → C array (no xxd/od tricks)
    python3 - "$cls" "$varname" "$header" <<'PYEOF'
import sys, os

cls_path, varname, header = sys.argv[1], sys.argv[2], sys.argv[3]
with open(cls_path, 'rb') as f:
    data = f.read()

cols = 16
lines = []
for i in range(0, len(data), cols):
    chunk = data[i:i+cols]
    lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk))

hex_block = ',\n'.join(lines)

with open(header, 'w') as f:
    f.write(f'/* Auto-generated by cldc/gen_headers.sh -- do not edit */\n')
    f.write(f'static unsigned char {varname}[] = {{\n{hex_block}\n}};\n')
    f.write(f'static unsigned int  {varname}_len = {len(data)};\n')
PYEOF

    len_bytes=$(wc -c < "$cls" | tr -d ' ')
    echo "  → generated/${base}.h  (${len_bytes} bytes, var: ${varname})"
done

echo "[cldc] All headers up to date."
